//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace svcGangManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CHRISEntities : DbContext
    {
        public CHRISEntities()
            : base("name=CHRISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
    
        public virtual ObjectResult<stpGetJobCodeInfo_Result> stpGetJobCodeInfo(string jobCode)
        {
            var jobCodeParameter = jobCode != null ?
                new ObjectParameter("JobCode", jobCode) :
                new ObjectParameter("JobCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stpGetJobCodeInfo_Result>("stpGetJobCodeInfo", jobCodeParameter);
        }
    }
}
