//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace svcGangManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string SSN { get; set; }
        public bool Contract { get; set; }
        public Nullable<int> Dept { get; set; }
        public string First_Name { get; set; }
        public string First_Init { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public string HomePhone { get; set; }
        public bool Unlisted { get; set; }
        public string HomePhone_2 { get; set; }
        public string TravelAcctNo { get; set; }
        public Nullable<System.DateTime> Birth_Date { get; set; }
        public Nullable<System.DateTime> Hire_Date { get; set; }
        public bool Sex { get; set; }
        public Nullable<int> Marital_Status_ID { get; set; }
        public Nullable<int> MF_Code { get; set; }
        public string RR_Hired { get; set; }
        public bool Term { get; set; }
        public Nullable<System.DateTime> Term_Date { get; set; }
        public Nullable<int> Term_ID { get; set; }
        public Nullable<short> Injuries { get; set; }
        public Nullable<System.DateTime> Last_Injured_Date { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Status_Date { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Remarks_Date { get; set; }
        public bool Furloughed { get; set; }
        public Nullable<float> Operating_Test_Score { get; set; }
        public Nullable<System.DateTime> Operating_Test_Date { get; set; }
        public Nullable<float> FRA_Test_Score { get; set; }
        public Nullable<System.DateTime> FRA_Test_Date { get; set; }
        public Nullable<float> Hazard_Test_Score { get; set; }
        public Nullable<System.DateTime> Hazard_Test_Date { get; set; }
        public bool Rule_17 { get; set; }
        public Nullable<System.DateTime> Rule_17_Date { get; set; }
        public string Payroll_Status { get; set; }
        public bool Frozen { get; set; }
        public string Jobcode { get; set; }
        public Nullable<System.DateTime> Driver_s_License_Exp_Date { get; set; }
        public Nullable<System.DateTime> Med { get; set; }
        public Nullable<System.DateTime> Annual_Rev_Driv_Rec { get; set; }
        public Nullable<System.DateTime> Violation { get; set; }
        public bool CRT { get; set; }
        public bool Cert { get; set; }
        public bool DRT { get; set; }
        public bool WED { get; set; }
        public bool EMP { get; set; }
        public bool CWE { get; set; }
        public bool EAP { get; set; }
        public Nullable<int> CDL_Class_ID { get; set; }
        public bool LOG { get; set; }
        public bool DRQ { get; set; }
        public bool Exclude_As_Driver { get; set; }
        public string Spouse { get; set; }
        public Nullable<short> Num_Dependents { get; set; }
        public string Spouse_Employer { get; set; }
        public string Spouse_Position { get; set; }
        public string Emergency_Phone { get; set; }
        public string Relatives_with_Company { get; set; }
        public Nullable<int> School_Circle { get; set; }
        public string School_Name { get; set; }
        public string School_Year { get; set; }
        public string School_Degree { get; set; }
        public string School_Major { get; set; }
        public Nullable<int> College_Circle { get; set; }
        public string College_Name { get; set; }
        public string College_Year { get; set; }
        public string College_Degree { get; set; }
        public string College_Major { get; set; }
        public Nullable<int> Graduate_Circle { get; set; }
        public string Graduate_Name { get; set; }
        public string Graduate_Year { get; set; }
        public string Graduate_Degree { get; set; }
        public string Graduate_Major { get; set; }
        public Nullable<int> Other_Circle { get; set; }
        public string Other_Name { get; set; }
        public string Other_Year { get; set; }
        public string Other_Degree { get; set; }
        public string Other_Major { get; set; }
        public string Skills { get; set; }
        public string Military_Branch { get; set; }
        public Nullable<System.DateTime> Military_Start { get; set; }
        public Nullable<System.DateTime> Military_End { get; set; }
        public string Military_Rank { get; set; }
        public string Misc { get; set; }
        public string Union_ { get; set; }
        public string EEO { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Region { get; set; }
        public string CS_Status { get; set; }
        public string CS_PR_Division { get; set; }
        public string Job_Status { get; set; }
        public Nullable<System.DateTime> upsize_ts { get; set; }
        public string Feb7 { get; set; }
        public Nullable<int> Feb7Reason { get; set; }
        public Nullable<System.DateTime> Feb7Date { get; set; }
        public string First_Name_Used { get; set; }
        public Nullable<System.DateTime> ApplicationForEmployment { get; set; }
        public Nullable<System.DateTime> RoadTestCert { get; set; }
        public Nullable<System.DateTime> WrittenCert { get; set; }
        public Nullable<System.DateTime> DrugTestCert { get; set; }
        public Nullable<System.DateTime> CommercialIDL { get; set; }
        public Nullable<System.DateTime> FMCSafetyBook { get; set; }
        public string DriversLicense { get; set; }
        public bool CDLRequired { get; set; }
        public string LicenseState { get; set; }
        public Nullable<int> tmpCRImport { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> FedMotorSafetyBook { get; set; }
        public Nullable<int> DrugTest { get; set; }
        public Nullable<int> Supervisor { get; set; }
        public string FHWYRestricts { get; set; }
        public Nullable<System.DateTime> FirstHireDate { get; set; }
        public Nullable<System.DateTime> LogsReceived { get; set; }
        public Nullable<int> ConsentForm { get; set; }
        public bool HideOfficer { get; set; }
        public string SSN_NoDash { get; set; }
        public string Racf_id { get; set; }
        public string address_temp { get; set; }
        public string zip_temp { get; set; }
        public Nullable<bool> NSMA { get; set; }
        public bool ShowInPhoneList { get; set; }
        public bool PermitOnly { get; set; }
        public bool AdvancedSignalTraining { get; set; }
        public string Personnel_Initials { get; set; }
        public Nullable<bool> QualifiedForRR { get; set; }
        public string Cell { get; set; }
        public string Pager { get; set; }
        public string Static_Fax_Home { get; set; }
        public string Email { get; set; }
        public Nullable<short> Vacation_Days { get; set; }
        public Nullable<bool> Private { get; set; }
        public string Static_Fax_Office { get; set; }
        public int EmpID { get; set; }
        public Nullable<bool> TwicCard { get; set; }
        public Nullable<System.DateTime> TWICExpDate { get; set; }
        public Nullable<bool> FMCSA { get; set; }
        public string PersonalEmail { get; set; }
        public Nullable<bool> Grandfather { get; set; }
        public Nullable<bool> CDLRep { get; set; }
        public string EmergencyName { get; set; }
        public string EmergencyPhone1 { get; set; }
        public string EmergencyPhone2 { get; set; }
        public Nullable<float> SAT_Score { get; set; }
        public Nullable<System.DateTime> SAT_Date { get; set; }
        public Nullable<bool> Hide { get; set; }
        public string Position_ID { get; set; }
        public Nullable<System.DateTime> JobCode_StartDate { get; set; }
        public Nullable<int> MWSKeyLock { get; set; }
        public Nullable<bool> MWSKeyLockReceiptedFor { get; set; }
        public Nullable<System.DateTime> CWRTrainingDate { get; set; }
        public string QualifiedBy { get; set; }
        public Nullable<System.DateTime> DateQualified { get; set; }
        public Nullable<bool> RRCard { get; set; }
        public Nullable<System.DateTime> DateRescind { get; set; }
    }
}
