//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace svcGangManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gangs
    {
        public int GangID { get; set; }
        public string Gang { get; set; }
        public string Supervisor { get; set; }
        public string Store { get; set; }
        public string Rin { get; set; }
        public string Func { get; set; }
        public string Afe { get; set; }
        public Nullable<int> GangTypeID { get; set; }
        public string SwitchStore { get; set; }
    }
}
