//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace svcGangManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gang_Type
    {
        public int Gang_Type_Code { get; set; }
        public string Gang_Type1 { get; set; }
        public string Gang_Prefix { get; set; }
        public Nullable<double> MPVariance { get; set; }
        public Nullable<int> Order { get; set; }
    }
}
