//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace svcGangManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public string JobCode { get; set; }
        public string NextJobCode { get; set; }
        public string Roster { get; set; }
        public string DPG_Zones { get; set; }
        public string Gang { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public Nullable<bool> Fixed_HQ { get; set; }
        public string Headquarters { get; set; }
        public string Phone { get; set; }
        public string Microwave { get; set; }
        public string Machine_Type { get; set; }
        public string Machine_Number { get; set; }
        public string District { get; set; }
        public string Division { get; set; }
        public Nullable<System.DateTime> Start_Time { get; set; }
        public Nullable<System.DateTime> Stop_Time { get; set; }
        public Nullable<System.DateTime> Start_Meal { get; set; }
        public Nullable<System.DateTime> Stop_Meal { get; set; }
        public Nullable<decimal> Salary_Min { get; set; }
        public Nullable<decimal> Salary_Mid { get; set; }
        public Nullable<decimal> Salary_Max { get; set; }
        public Nullable<decimal> Pay_Rate { get; set; }
        public string Pay_Period { get; set; }
        public string Points { get; set; }
        public Nullable<int> Cost_Center { get; set; }
        public Nullable<bool> Permanent_ { get; set; }
        public Nullable<System.DateTime> Perm_Date { get; set; }
        public string Group_ { get; set; }
        public Nullable<short> Group_Type { get; set; }
        public string RM_District { get; set; }
        public Nullable<System.DateTime> PR_Ending_Date { get; set; }
        public string Supervisor { get; set; }
        public string Division_Engineer { get; set; }
        public Nullable<bool> Mail { get; set; }
        public Nullable<bool> DPG_Mail { get; set; }
        public string JP_Number { get; set; }
        public string Pay_ID { get; set; }
        public string PagerNumber { get; set; }
        public string PagerPIN { get; set; }
        public string RestDays { get; set; }
        public string StandByDay { get; set; }
        public string Region { get; set; }
        public string Vehicle_No { get; set; }
        public string Job_Desc { get; set; }
        public string Milepost { get; set; }
        public string Rule_No { get; set; }
        public string Div { get; set; }
        public string Dept { get; set; }
        public string Position { get; set; }
        public Nullable<int> RateCode { get; set; }
        public string HomeZone { get; set; }
        public Nullable<bool> CDLRequired { get; set; }
        public string Fax { get; set; }
        public string TrackSched { get; set; }
        public Nullable<int> NumAsstSuprv { get; set; }
        public Nullable<double> MainLineMiles { get; set; }
        public Nullable<double> YardTrackMiles { get; set; }
        public Nullable<double> TotalMiles { get; set; }
        public Nullable<double> MaxMainLineTotal { get; set; }
        public string SupervisorJobCode { get; set; }
        public string Division_EngineerJobCode { get; set; }
        public Nullable<bool> CSGangJob { get; set; }
        public string Chief_Engineer { get; set; }
        public Nullable<int> OfficerRank { get; set; }
        public string MobilePhone { get; set; }
        public string CellPhone { get; set; }
        public string gangnumber { get; set; }
        public Nullable<bool> Driver1026000 { get; set; }
        public Nullable<bool> CRMail { get; set; }
        public Nullable<bool> NWMail { get; set; }
        public Nullable<bool> WABMail { get; set; }
        public Nullable<System.DateTime> Schedule_Date { get; set; }
        public string PayBand { get; set; }
        public bool HmAddrIsMailAddr { get; set; }
        public Nullable<int> ProgMaintGangID { get; set; }
        public string PositionID { get; set; }
        public int JobID { get; set; }
    }
}
