//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace svcGangManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProdGangEntities : DbContext
    {
        public ProdGangEntities()
            : base("name=ProdGangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gang_Type> Gang_Type { get; set; }
        public virtual DbSet<Gang> Gangs { get; set; }
        public virtual DbSet<ThermiteWelding_JsonDataLog> ThermiteWelding_JsonDataLog { get; set; }
    
        public virtual ObjectResult<stpGetGangSupervisorInfo_Result> stpGetGangSupervisorInfo(string gangid)
        {
            var gangidParameter = gangid != null ?
                new ObjectParameter("gangid", gangid) :
                new ObjectParameter("gangid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stpGetGangSupervisorInfo_Result>("stpGetGangSupervisorInfo", gangidParameter);
        }
    }
}
