//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace svcGangManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDivision
    {
        public int DivisionID { get; set; }
        public string DivisionName { get; set; }
        public string DivisionCode { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
